# Friendly name for the workflow in GitHub
name: Continuous Integration (CI)
# Run the workflow each time code is pushed, or when a pull-request is created
on: [push, pull_request]

jobs:

  # Run security scans
  scan:
    # Configure the job 
    name: Run security scans
    runs-on: ubuntu-latest

    # Steps to run
    steps:
    # Set up prerequisites for tests
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1

    # DevSkim
    # - Some CI support inbuilt tasks and scans, for  ease of use
    # - We could install and run DevSkim directly, but we can do it more easily using the DevSkim action
    # - See docs at: https://github.com/microsoft/DevSkim-Action 
    - uses: microsoft/devskim-action@v1
      with:
        directory-to-scan: /
        should-scan-archives: false
        output-filename: devskim-results.sarif
        output-directory: .scans/output

    # Publish the scan results as an artifact
    - uses: actions/upload-artifact@v2
      with: 
        name: scan-results
        path: .scans/output
    
   #TODO Scan aimed at SQL injection vulnerability
